server:
  port: 8439

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/springbatchpractice
    username: root
    password: roots
  batch:
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true

