server.port=8439

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3309/springbatchpractice
spring.datasource.username=root
spring.datasource.password=roots

#spring batch
spring.batch.jdbc.initialize-schema=always